controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    methods: ["GET"]
    controller: App\Controller\DefaultController::index
